version: '3.9'
services:
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: 1
    networks:
      - my-network
    volumes:
      - ./data/mysql/data:/var/lib/mysql
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - my-network
    depends_on:
      - mysql

#  mongodb:
#    image: mongo
#    container_name: mongodb
#    hostname: mongodb
#    restart: always
#    ports:
#      - 27017:27017
#    networks:
#      - my-network
#    volumes:
#      - ./data/mongodb/data:/data/db
#      - ./data/mongodb/scripts:/scripts
#    command: ["/scripts/setup.sh"]
#  mongo-express:
#    image: mongo-express
#    container_name: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_SERVER: mongodb
#      ME_CONFIG_MONGODB_PORT: 27017
#    networks:
#      - my-network
#    depends_on:
#      - mongodb
networks:
  my-network:
    driver: bridge
    name: my-network